In [3]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from pandas import DataFrame as df

首先先把之前的指数都画出来,进行相同的标准化处理,以1000作为起始值

In [4]:
import pickle

In [6]:
all_index_dic = pd.read_pickle('../../src/pickle/all_index_dic.pkl')
all_index_dic['CSI_300']

                open      high       low     close       volume
date
2008-05-05  4015.212  4061.472  3972.561  4055.779   6253407300
2008-05-06  4021.073  4075.575  3961.344  4010.888   5845928000
2008-05-07  3986.129  4042.407  3821.107  3821.319   5445770600
2008-05-08  3774.044  3926.004  3761.280  3925.041   4405566800
2008-05-09  3960.886  3973.058  3806.519  3878.924   5365592900
...              ...       ...       ...       ...          ...
2026-07-20  4575.671  4628.799  4521.181  4598.321  33311605800
2026-07-21  4630.853  4739.233  4566.281  4739.229  34540359000
2026-07-22  4710.660  4772.082  4692.833  4717.244  28555635700
2026-07-23  4735.171  4737.509  4698.872  4728.002  24733167500
2026-07-24  4685.408  4704.084  4642.939  4649.192  22126121200

[4430 rows x 5 columns]

因为数据的时间跨度不同,以最迟的时间为共同的起始时间,选定为2012-05-02

In [11]:
# CSI_300 = all_index_dic['CSI_300']
CSI_300 = CSI_300[CSI_300.index>='2012-05-09']
display(CSI_300)

                open      high       low     close       volume
date
2012-05-09  2685.187  2685.187  2655.322  2657.514   5840028400
2012-05-10  2657.870  2667.675  2649.380  2657.214   4696257600
2012-05-11  2652.313  2666.566  2636.523  2636.917   4100614400
2012-05-14  2653.806  2656.284  2613.349  2615.534   5208248400
2012-05-15  2597.644  2618.175  2591.598  2617.374   4576727200
...              ...       ...       ...       ...          ...
2026-07-20  4575.671  4628.799  4521.181  4598.321  33311605800
2026-07-21  4630.853  4739.233  4566.281  4739.229  34540359000
2026-07-22  4710.660  4772.082  4692.833  4717.244  28555635700
2026-07-23  4735.171  4737.509  4698.872  4728.002  24733167500
2026-07-24  4685.408  4704.084  4642.939  4649.192  22126121200

[3454 rows x 5 columns]

In [12]:
# A_500 = all_index_dic['A_500']
A_500 = A_500[A_500.index>='2012-05-09']
display(A_500)

                open      high       low     close       volume
date
2012-05-09  2783.926  2783.926  2755.094  2755.228   7012241399
2012-05-10  2755.050  2764.947  2749.575  2755.686   5664663958
2012-05-11  2751.332  2763.421  2737.720  2737.720   5277476815
2012-05-14  2754.683  2754.683  2717.360  2717.594   6530717239
2012-05-15  2699.958  2719.389  2694.259  2719.155   5861097867
...              ...       ...       ...       ...          ...
2026-07-20  5640.161  5689.288  5517.736  5622.822  43173580900
2026-07-21  5662.597  5840.071  5561.531  5839.907  45783622600
2026-07-22  5803.258  5889.696  5772.122  5803.773  38907146900
2026-07-23  5824.260  5833.698  5772.924  5814.557  33470105300
2026-07-24  5751.544  5787.069  5698.086  5703.869  30308512600

[3454 rows x 5 columns]

In [10]:
metal_index = all_index_dic['metal']
display(metal_index)

,prevclose,open,high,low,close,volume,amount
date,,,,,,,
2012-05-09,5768.798,5683.090,5723.061,5605.902,5607.605,740022700,18089451520
2012-05-10,NaN,5582.521,5702.406,5580.490,5672.149,630264000,15322286080
2012-05-11,NaN,5662.713,5714.175,5597.076,5598.492,610345300,13937305600
2012-05-14,NaN,5643.467,5655.063,5482.461,5486.062,561489500,12728383488
2012-05-15,NaN,5413.958,5462.289,5348.687,5460.971,550420900,11533073408
...,...,...,...,...,...,...,...
2026-07-20,NaN,7979.533,8038.483,7764.135,7899.215,4252373700,83899245945
2026-07-21,NaN,7982.533,8250.876,7836.970,8250.876,4717327400,98284572699
2026-07-22,NaN,8309.978,8646.986,8309.978,8521.360,5508479900,118750345435
2026-07-23,NaN,8570.441,8933.202,8494.093,8796.837,5435546900,115687162016
2026-07-24,NaN,8505.359,8621.259,8335.025,8372.073,4145011300,83404703912

In [38]:
cap_index = all_index_dic['cap']
cap_index = cap_index[cap_index.index>='2012-05-09']
display(cap_index)

date
2012-05-09     990.717618
2012-05-10     993.260878
2012-05-11     984.505107
2012-05-14     975.513759
2012-05-15     975.419625
                 ...
2026-07-20    4827.178200
2026-07-21    5033.940032
2026-07-22    5366.790961
2026-07-23    5481.074967
2026-07-24    5213.366389
Length: 3454, dtype: float64

In [14]:
weight_index = all_index_dic['weight']
weight_index = weight_index[weight_index.index>='2012-05-09']
display(weight_index)

date
2012-05-09     988.432415
2012-05-10     989.984969
2012-05-11     980.788921
2012-05-14     971.462750
2012-05-15     971.069149
                 ...
2026-07-20    5123.428722
2026-07-21    5331.111009
2026-07-22    5683.318623
2026-07-23    5810.440569
2026-07-24    5530.385078
Length: 3454, dtype: float64

In [29]:
equal_index = all_index_dic['equal']
equal_index = equal_index[equal_index.index>='2012-05-09']
display(weight_index)

date
2012-05-09     988.432415
2012-05-10     989.984969
2012-05-11     980.788921
2012-05-14     971.462750
2012-05-15     971.069149
                 ...
2026-07-20    5123.428722
2026-07-21    5331.111009
2026-07-22    5683.318623
2026-07-23    5810.440569
2026-07-24    5530.385078
Length: 3454, dtype: float64

将指数归一化,统一变成1000开头的数字,比较他们的变化率

In [31]:
CSI_300 = CSI_300['close']/CSI_300['close'].iloc[0]*1000
display(CSI_300)

date
2012-05-09    1000.000000
2012-05-10     999.887113
2012-05-11     992.249523
2012-05-14     984.203282
2012-05-15     984.895658
                 ...
2026-07-20    1730.309229
2026-07-21    1783.331715
2026-07-22    1775.058946
2026-07-23    1779.107090
2026-07-24    1749.451555
Name: close, Length: 3454, dtype: float64

In [32]:
A_500 = A_500['close'] / A_500['close'].iloc[0] * 1000
display(A_500)

date
2012-05-09    1000.000000
2012-05-10    1000.166229
2012-05-11     993.645535
2012-05-14     986.340876
2012-05-15     986.907436
                 ...
2026-07-20    2040.782832
2026-07-21    2119.573044
2026-07-22    2106.458340
2026-07-23    2110.372354
2026-07-24    2070.198546
Name: close, Length: 3454, dtype: float64

In [33]:
metal_index = metal_index['close'] / metal_index['close'].iloc[0] * 1000
display(metal_index)

date
2012-05-09    1000.000000
2012-05-10    1011.510083
2012-05-11     998.374886
2012-05-14     978.325328
2012-05-15     973.850869
                 ...
2026-07-20    1408.661095
2026-07-21    1471.372538
2026-07-22    1519.607747
2026-07-23    1568.733354
2026-07-24    1492.985508
Name: close, Length: 3454, dtype: float64

In [39]:
weight_index = weight_index/ weight_index[0] *1000
equal_index = equal_index / equal_index[0] *1000
cap_index = cap_index / cap_index[0] * 1000

/var/folders/nm/mph7gkl57w5_rd8w9fgp9c5r0000gp/T/ipykernel_75327/1672919466.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  weight_index = weight_index/ weight_index[0] *1000
/var/folders/nm/mph7gkl57w5_rd8w9fgp9c5r0000gp/T/ipykernel_75327/1672919466.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  equal_index = equal_index / equal_index[0] *1000
/var/folders/nm/mph7gkl57w5_rd8w9fgp9c5r0000gp/T/ipykernel_75327/1672919466.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  cap_index = cap_index / cap_index[0] * 1000

In [ ]:
fig,ax = plt.subplots(figsize=(30,6))

fig, ax = plt.subplots(figsize=(30, 6))

sns.lineplot(CSI_300, ax=ax, label='CSI_300')
sns.lineplot(A_500, ax=ax, label='A_500')
sns.lineplot(metal_index, ax=ax, label='metal')
sns.lineplot(equal_index, ax=ax, label='equal')
sns.lineplot(weight_index, ax=ax, label='weight')
sns.lineplot(cap_index, ax=ax, label='cap')

ax.set_title('归一化指数比较')
ax.set_ylabel('归一化值')
ax.legend()